---
galaxy_info:
  author: Alex Kretzschmar
  description: Adds repos to RHEL
  issue_tracker_url: https://github.com/ironicbadger/ansible-role-mount/issues
  license: GPLv2
  min_ansible_version: 2.4
  platforms:
  - name: EL
    versions:
      - 7
dependencies: []
